### PR TITLE
Force Simulator Language fix

### PR DESCRIPTION
**Pull request by CBeloch**
There are some issues with the NSDateFormatter not using the language defined with the parameters and still using the english locale to create a localized date string.
This patch adds the `force_simulator_language`option which is currently `false` by  default that will patch the simulators to the correct language defined in the Snapfile.

This prevents an ugly fix in the project code to set the correct locale for NSDateFormatter.
Also `NSLocale.currentLocale` returns `en_US` if the simulator itself is not set to the desired language

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for the pull request. I'm not 100% sure of why that's necessary, do you know a way how I reproduce this issue?

**Comment by CBeloch** [comment]
I have an issue that the current language switch isn't working when I have a UILabel that is filled with a localized date string.

```swift
let formatter = NSDateFormatter()
formatter.dateStyle = .MediumStyle
self.myLabel.text = formatter.stringFromDate(NSDate())
```

In my cases (across multiple app), this will always generate a en_US locale style date. No matter what I use in Xcode as Application Language and Region (which is also set by snapshot). Also the "Carrier" string in the status bar is also an indication for this issue as this never changed.

**Comment by Philluxx** [comment]
And even the time in the status bar shows the time in US style (e.g. 2:53 pm) instead of the desired region (for DE e.g. 14:53). Setting the region and locale manually in each simulator will work as an workaround until the next simulator reset.

**Comment by DominicFrei** [comment]
In addition to the date formatter and the status bar, I sometimes import data into the Realm database localised depending on the language. Wrong data is imported because of that issue.

A change of language in the simulator would here be helpful, too.
Good idea @CBeloch :+1:

**Comment by CBeloch** [comment]
This is really strange. I wanted to create a sample app to show the problem, but except for the "Carrier" not being localized everything worked correctly. On my problem app I still have the issue that `NSLocale.currentLocale` is set to `en_US` even if i take screenshots with `de_DE`.
I updated Snapshot and my SnapshotHelper.swift and using `setupSnapshot` instead of `setLanguage` in the UITest used for snapshot.

**Comment by DominicFrei** [comment]
Seems like you changed something, that stopped snapshot from working.

@CBeloch Could you go back in your 'bigger' project's history and try to find a commit where it works? (git bisect i.e.)

**Comment by CBeloch** [comment]
@DominicFrei Never worked correctly in my big project

**Comment by DominicFrei** [comment]
@CBeloch Even though when you go back in history to where the big project was exactly the same as the newly generated project from the Xcode templates?

**Comment by mfurtak** [comment]
I'm going to close this due to inactivity. Please feel free to continue the conversation, and we can reopen if needed! :+1:

**Pull request closed without merging**
